[build]
builder = "nixpacks"

[deploy]
startCommand = "node server.js"
restartPolicyType = "always"
restartPolicyMaxRetries = 10
healthcheckPath = "/api/health"
healthcheckTimeout = 300

[[services]]
name = "SULAV VPS"
